### ISSUE TITLE
How to include this package?

### ISSUE THREAD

**Issue by ivelichkovich** [aspenmesh/istio-client-go#12]
dep ensure -add github.com/aspenmesh/istio-client-go doesn't work because there's no go files in the root directory.

How do I go about including this in my package?

**Comment by nrjpoddar** [comment]
Hi @ivelichkovich, if you include any of the packages under `github.com/aspenmesh/istio-client-go/pkg` in your application then dep should automatically pull in the right dependency by just running `dep ensure`.

We use it like that here: `https://github.com/aspenmesh/istio-vet/blob/master/pkg/istioclient/client.go#L21`.
