### ISSUE TITLE
The Virtualservice client does populate HTTPMatchRequest object 

### ISSUE THREAD

**Issue by tkishore1192** [aspenmesh/istio-client-go#13]
While looking for the spec part of the virtualservice : 

{{[reviews.prod.svc.cluster.local] [] [match:<uri:<> > route:<destination:<host:"reviews.prod.svc.cluster.local" port:<> > > ] [] [] [] {} [] 0}}

The HTTPMatchRequest is empty and also the port.

**Comment by ivelichkovich** [comment]
Yeah I'm seeing it populate the match request but if I iterate through the Headers returned I found the proper keys however the MatchType object value null in the header map is null

**Comment by ivelichkovich** [comment]
Yeah I have a simple api that just returns a virtual service and it always looks like this

`{
  "metadata": {
    "name": "reviews",
    "namespace": "istio-demo",
    "selfLink": "/apis/networking.istio.io/v1alpha3/namespaces/istio-demo/virtualservices/reviews",
    "uid": "1192534a-5584-11e9-a955-12670029b5ae",
    "resourceVersion": "132591918",
    "generation": 1,
    "creationTimestamp": "2019-04-02T20:15:33Z"
  },
  "spec": {
    "hosts": [
      "reviews"
    ],
    "http": [
      {
        "match": [
          {
            "headers": {
              "end-user": {
                "MatchType": null
              },
              "other-header": {
                "MatchType": null
              }
            }
          }
        ],
        "route": [
          {
            "destination": {
              "host": "reviews",
              "subset": "v2"
            }
          }
        ]
      },
      {
        "route": [
          {
            "destination": {
              "host": "reviews",
              "subset": "v1"
            }
          }
        ]
      }
    ]
  }
}`

**Comment by ivelichkovich** [comment]
Same with faults and http delay type
`  http:
    - route:
        - destination:
            host: details
            subset: v1
          weight: 63
        - destination:
            host: details
            subset: v2
          weight: 37
      fault:
        delay:
          percent: 100
          HttpDelayType: null`

**Comment by nrjpoddar** [comment]
@tkishore1192 please follow the comment here: https://github.com/aspenmesh/istio-client-go/issues/14#issuecomment-480888185 as the underlying issues are the same.

**Comment by nrjpoddar** [comment]
Fixed by #16 PR from @francoispradeau

@tkishore1192  can you try now?

**Comment by tkishore1192** [comment]
This is great! It's able to populate the value now. From what I understand, we use jsonpb because istio proto buf, but could you let me know how adding marshal and unmarshal methods help in extracting values? Is this method overriding any methods?
