### ISSUE TITLE
VirtualService Deserialization Issues

### ISSUE THREAD

**Issue by ivelichkovich** [aspenmesh/istio-client-go#14]
I commented on this issue but I thought I should open a new one for this
https://github.com/aspenmesh/istio-client-go/issues/13

the match selectors and http faults (and probably others but I haven't ran into those yet) are not deserializing properly. 

For this virtualservice
`spec:
  hosts:
  - details
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percent: 100
    route:
    - destination:
        host: details
        subset: v1
      weight: 63
    - destination:
        host: details
        subset: v2
      weight: 37`

 I get this returned
`http: - route: - destination: host: details subset: v1 weight: 63 - destination: host: details subset: v2 weight: 37 fault: delay: percent: 100 HttpDelayType: null`

and for this virtualservice 
`  http:
  - match:
    - headers:
        end-user:
          exact: jason
        other-header:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1`

I get this returned
`spec:
  hosts:
    - reviews
  http:
    - match:
        - headers:
            end-user:
              MatchType: null
            other-header:
              MatchType: null
      route:
        - destination:
            host: reviews
            subset: v2
    - route:
        - destination:
            host: reviews
            subset: v1`

**Comment by nrjpoddar** [comment]
@ivelichkovich Thanks for filing this issue and I apologize for the late response. It appears that `oneof` are not getting deserialized correctly e.g. https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L1053. 

The generated Go code https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.pb.go#L2323 is missing `json` tag and so the default decoder is not serializing this correctly.

We have an internal custom decoder which handles this case but if you're using default Kubernetes decoder which relies on JSON these objects don't get deserialized with all fields populated.

**Comment by nrjpoddar** [comment]
@ivelichkovich we are working on addressing this by adding customer Marshalers/Unmarshalers which will use `jsonpb`. 

Will update this issue when we have a fix.

**Comment by nrjpoddar** [comment]
Fixed by https://github.com/aspenmesh/istio-client-go/pull/16 PR from @francoispradeau 

@ivelichkovich can you try now?
