### ISSUE TITLE
please consider adding all networking objects (in dire need of ServiceEntry)

### ISSUE THREAD

**Issue by sdake** [aspenmesh/istio-client-go#18]
Hi.  I have submitted a PR here to a fork of your repository which has a more complete implementation of the API:

https://github.com/michaelkipper/istio-client-go/pull/14

Are there plans to improve this codebase from Aspenmesh?

I would have submitted my PR here, but SEs are not implemented in master.

Cheers
-steve

**Comment by nrjpoddar** [comment]
Hi @sdake, yes we plan to add these APIs soon. We initially added the resources we needed for istio-vet, but now we are realizing that there’s a broader need for istio-client-go.

Adding the new resources is pretty easy so we can do it in short order. I’m guessing ServiceEntry, Gateway are the most urgent. Please specify what else you need and I will make sure it gets added next.

**Comment by nrjpoddar** [comment]
@sdake try the latest version, it has `Gateway` & `ServiceEntry` resources.

**Comment by sdake** [comment]
@nrjpoddar Thank you.  I also require `EnvoyFilter` - PR here if you want to borrow: https://github.com/michaelkipper/istio-client-go/pull/19

I'll see if I can find time today to submit the work I submitted there here.
