### ISSUE TITLE
why are certain deepcopy functions for Istio resources not auto-generated ?

### ISSUE THREAD

**Issue by kidiyoor** [aspenmesh/istio-client-go#22]
can anyone explain why this function was not auto-generated - https://github.com/aspenmesh/istio-client-go/blob/master/pkg/apis/networking/v1alpha3/destination_rule.go#L87

Is there another work around ?

**Comment by nrjpoddar** [comment]
@kidiyoor the issue is that `istio/api` doesn't add the `deepcopy` annotations https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.pb.go and so it cannot be auto-generated.

**Comment by nrjpoddar** [comment]
There are 2 ways to solve this other than what we have done i.e. a shallow copy:

* Get istio/api to add the appropriate annotations for `deepcopy`
* Copy over the generated go files and add the annotations manually. This has the drawback that things might get out of sync quickly.
